In [5]:
import pymongo
db_name = input("Enter name of your database: ")
collection_name = input("Enter name of your collection: ")
client = pymongo.MongoClient(input("Enter your connection string: "))
db = client.test
db2 = client[db_name]
coll1 = db2[collection_name]

Enter name of your database: carbon_nanotubes
Enter name of your collection: carbon_nanotubes_db_1
Enter your connection string: mongodb+srv://Akmongo:amongo@cluster0.sdfyq.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

In [3]:
import mc

In [ ]:
mc.data_transfer(coll1)

In [6]:
import pandas as pd
l = []
for i in coll1.find():
    l.append(i)
pd.DataFrame(l)

,_id,Chiral indice n,Chiral indice m,Initial atomic coordinate u,Initial atomic coordinate v,Initial atomic coordinate w,Calculated atomic coordinates u',Calculated atomic coordinates v',Calculated atomic coordinates w'
0,6215b8a9e5457239043adbed,2.0,1.0,0.717298,0.642129,0.231319,0.738414,0.656750,0.232369
1,6215b8a9e5457239043adbee,2.0,1.0,0.489336,0.303751,0.088462,0.477676,0.263221,0.088712
2,6215b8a9e5457239043adbef,2.0,1.0,0.413957,0.632996,0.040843,0.408823,0.657897,0.039796
3,6215b8a9e5457239043adbf0,2.0,1.0,0.334292,0.543401,0.159890,0.303349,0.558807,0.157373
4,6215b8a9e5457239043adbf1,2.0,1.0,0.510664,0.696249,0.255128,0.496977,0.725608,0.255970
...,...,...,...,...,...,...,...,...,...
10715,6215b8a9e5457239043b05c8,12.0,6.0,0.834201,0.399891,0.891270,0.841858,0.405882,0.891356
10716,6215b8a9e5457239043b05c9,12.0,6.0,0.698374,0.244710,0.962699,0.706555,0.248416,0.962833
10717,6215b8a9e5457239043b05ca,12.0,6.0,0.923823,0.568913,0.819842,0.929403,0.576284,0.819879
10718,6215b8a9e5457239043b05cb,12.0,6.0,0.934978,0.602319,0.938889,0.941844,0.610608,0.938755
10719,6215b8a9e5457239043b05cc,12.0,6.0,0.953664,0.698374,0.962699,0.961243,0.707812,0.962605

In [15]:
ag = coll1.aggregate(
    [{
        '$group':{'_id':'$Chiral indice m','No of records':{'$sum':1}}
    }])
for i in ag:
    print(i)

{'_id': 1.0, 'No of records': 1786}
{'_id': 2.0, 'No of records': 2419}
{'_id': 3.0, 'No of records': 1539}
{'_id': 5.0, 'No of records': 1456}
{'_id': 6.0, 'No of records': 1588}
{'_id': 4.0, 'No of records': 1932}

In [17]:
ag = coll1.aggregate(
    [{
        '$group':{'_id':'$Chiral indice n','No of records':{'$sum':1}}
    }])
for i in ag:
    print(i)

{'_id': 12.0, 'No of records': 972}
{'_id': 8.0, 'No of records': 1772}
{'_id': 9.0, 'No of records': 1689}
{'_id': 11.0, 'No of records': 588}
{'_id': 6.0, 'No of records': 875}
{'_id': 3.0, 'No of records': 128}
{'_id': 5.0, 'No of records': 719}
{'_id': 2.0, 'No of records': 27}
{'_id': 4.0, 'No of records': 288}
{'_id': 7.0, 'No of records': 2126}
{'_id': 10.0, 'No of records': 1536}

In [9]:
l = []
for i in coll1.find({'Chiral indice n':2.0 , 'Chiral indice m': 1.0}):
    l.append(i)
pd.DataFrame(l)

,_id,Chiral indice n,Chiral indice m,Initial atomic coordinate u,Initial atomic coordinate v,Initial atomic coordinate w,Calculated atomic coordinates u',Calculated atomic coordinates v',Calculated atomic coordinates w'
0,6215b8a9e5457239043adbed,2.0,1.0,0.717298,0.642129,0.231319,0.738414,0.656750,0.232369
1,6215b8a9e5457239043adbee,2.0,1.0,0.489336,0.303751,0.088462,0.477676,0.263221,0.088712
2,6215b8a9e5457239043adbef,2.0,1.0,0.413957,0.632996,0.040843,0.408823,0.657897,0.039796
3,6215b8a9e5457239043adbf0,2.0,1.0,0.334292,0.543401,0.159890,0.303349,0.558807,0.157373
4,6215b8a9e5457239043adbf1,2.0,1.0,0.510664,0.696249,0.255128,0.496977,0.725608,0.255970
5,6215b8a9e5457239043adbf2,2.0,1.0,0.413957,0.632996,0.374176,0.390878,0.657645,0.374735
6,6215b8a9e5457239043adbf3,2.0,1.0,0.712552,0.554790,0.112271,0.750056,0.561494,0.114944
7,6215b8a9e5457239043adbf4,2.0,1.0,0.320995,0.298682,0.183700,0.281301,0.261433,0.182779
8,6215b8a9e5457239043adbf5,2.0,1.0,0.394742,0.279367,0.302747,0.350860,0.233500,0.302196
9,6215b8a9e5457239043adbf6,2.0,1.0,0.282702,0.357871,0.397985,0.229138,0.328729,0.398581
10,6215b8a9e5457239043adbf7,2.0,1.0,0.320995,0.298682,0.517033,0.278752,0.269615,0.517330
11,6215b8a9e5457239043adbf8,2.0,1.0,0.605258,0.720633,0.469414,0.613415,0.760009,0.469452
12,6215b8a9e5457239043adbf9,2.0,1.0,0.510664,0.696249,0.588462,0.521991,0.736991,0.588946
13,6215b8a9e5457239043adbfa,2.0,1.0,0.679005,0.701318,0.683700,0.718811,0.738577,0.682440
14,6215b8a9e5457239043adbfb,2.0,1.0,0.605258,0.720633,0.802747,0.649178,0.766301,0.801930
15,6215b8a9e5457239043adbfc,2.0,1.0,0.665708,0.456599,0.326557,0.680389,0.444562,0.327502
16,6215b8a9e5457239043adbfd,2.0,1.0,0.712552,0.554790,0.445605,0.737216,0.552056,0.443517
17,6215b8a9e5457239043adbfe,2.0,1.0,0.586043,0.367004,0.540843,0.591153,0.342069,0.540172
18,6215b8a9e5457239043adbff,2.0,1.0,0.665708,0.456599,0.659890,0.697242,0.441516,0.657521
19,6215b8a9e5457239043adc00,2.0,1.0,0.287448,0.445210,0.612271,0.249571,0.438057,0.614939
20,6215b8a9e5457239043adc01,2.0,1.0,0.282702,0.357871,0.731319,0.262916,0.343512,0.732213
21,6215b8a9e5457239043adc02,2.0,1.0,0.334292,0.543401,0.826557,0.320053,0.555754,0.827503
22,6215b8a9e5457239043adc03,2.0,1.0,0.287448,0.445210,0.945605,0.262054,0.448170,0.943402
23,6215b8a9e5457239043adc04,2.0,1.0,0.717298,0.642129,0.897985,0.770521,0.670869,0.898389
24,6215b8a9e5457239043adc05,2.0,1.0,0.489336,0.303751,0.755128,0.503560,0.274430,0.756290
25,6215b8a9e5457239043adc06,2.0,1.0,0.586043,0.367004,0.874176,0.609000,0.342123,0.875088
26,6215b8a9e5457239043adc07,2.0,1.0,0.394742,0.279367,0.969414,0.385666,0.240071,0.969157

In [10]:
coll2 = db2['Chiral_indice_n_1_Chiral_indice_m_2']
coll2.insert_many(l)

In [41]:
ag1 = coll2.aggregate(
    [{
        '$group':{'_id':'$Chiral indice m','No of records having chiral indice n equals 1 and Chiral indice m equals 2':{'$sum':1}}
    }])
for i in ag1:
    print(i)

{'_id': 1.0, 'No of records having chiral indice n equals 1 and Chiral indice m equals 2': 27}

In [51]:
la = []
ag2 = coll2.aggregate(
    [{
        '$group':{'_id':'$Chiral indice m','Mean of initial atomic coordinate u':{'$avg':'$Initial atomic coordinate u'},"mean of calculated atomic coordinates u'":{'$avg':"$Calculated atomic coordinates u'"}}
    }])
for i in ag2:
    la.append(i)
a = pd.DataFrame(la)
a['difference'] = a['Mean of initial atomic coordinate u']-a["mean of calculated atomic coordinates u'"]
a

,_id,Mean of initial atomic coordinate u,mean of calculated atomic coordinates u',difference
0,1.0,0.49337,0.491813,0.001557

In [52]:
la = []
ag2 = coll2.aggregate(
    [{
        '$group':{'_id':'$Chiral indice m','Mean of initial atomic coordinate v':{'$avg':'$Initial atomic coordinate v'},"mean of calculated atomic coordinates v'":{'$avg':"$Calculated atomic coordinates v'"}}
    }])
for i in ag2:
    la.append(i)
a = pd.DataFrame(la)
a['difference'] = a['Mean of initial atomic coordinate v']-a["mean of calculated atomic coordinates v'"]
a

,_id,Mean of initial atomic coordinate v,mean of calculated atomic coordinates v',difference
0,1.0,0.492544,0.491473,0.001071

In [53]:
la = []
ag2 = coll2.aggregate(
    [{
        '$group':{'_id':'$Chiral indice m','Mean of initial atomic coordinate w':{'$avg':'$Initial atomic coordinate w'},"mean of calculated atomic coordinates w'":{'$avg':"$Calculated atomic coordinates w'"}}
    }])
for i in ag2:
    la.append(i)
a = pd.DataFrame(la)
a['difference'] = a['Mean of initial atomic coordinate w']-a["mean of calculated atomic coordinates w'"]
a

,_id,Mean of initial atomic coordinate w,mean of calculated atomic coordinates w',difference
0,1.0,0.51086,0.510861,-7.037037e-07

In [55]:
la = []
ag2 = coll2.aggregate(
    [{
        '$group':{'_id':'$Chiral indice m','Highest initial atomic coordinate u':{'$max':'$Initial atomic coordinate u'},"Highest calculated atomic coordinates u'":{'$max':"$Calculated atomic coordinates u'"}}
    }])
for i in ag2:
    la.append(i)
a = pd.DataFrame(la)
a['difference'] = a['Highest initial atomic coordinate u']-a["Highest calculated atomic coordinates u'"]
a

,_id,Highest initial atomic coordinate u,Highest calculated atomic coordinates u',difference
0,1.0,0.717298,0.770521,-0.053223

In [54]:
la = []
ag2 = coll2.aggregate(
    [{
        '$group':{'_id':'$Chiral indice m','Highest initial atomic coordinate v':{'$max':'$Initial atomic coordinate v'},"Highest calculated atomic coordinates v'":{'$max':"$Calculated atomic coordinates v'"}}
    }])
for i in ag2:
    la.append(i)
a = pd.DataFrame(la)
a['difference'] = a['Highest initial atomic coordinate v']-a["Highest calculated atomic coordinates v'"]
a

,_id,Highest initial atomic coordinate v,Highest calculated atomic coordinates v',difference
0,1.0,0.720633,0.766301,-0.045668

In [56]:
la = []
ag2 = coll2.aggregate(
    [{
        '$group':{'_id':'$Chiral indice m','Highest initial atomic coordinate w':{'$max':'$Initial atomic coordinate w'},"Highest calculated atomic coordinates w'":{'$max':"$Calculated atomic coordinates w'"}}
    }])
for i in ag2:
    la.append(i)
a = pd.DataFrame(la)
a['difference'] = a['Highest initial atomic coordinate w']-a["Highest calculated atomic coordinates w'"]
a

,_id,Highest initial atomic coordinate w,Highest calculated atomic coordinates w',difference
0,1.0,0.969414,0.969157,0.000257

In [57]:
coll2.update_many({'Initial atomic coordinate u':{'$lt':0.49337}},{'$set':{'Initial atomic coordinate u':'less than mean'},'$currentDate':{'lastModified':True}})

In [60]:
l = []
for i in coll2.find():
    l.append(i)
pd.DataFrame(l)

,_id,Chiral indice n,Chiral indice m,Initial atomic coordinate u,Initial atomic coordinate v,Initial atomic coordinate w,Calculated atomic coordinates u',Calculated atomic coordinates v',Calculated atomic coordinates w',lastModified
0,6215b8a9e5457239043adbed,2.0,1.0,0.717298,0.642129,0.231319,0.738414,0.656750,0.232369,NaT
1,6215b8a9e5457239043adbee,2.0,1.0,less than mean,0.303751,0.088462,0.477676,0.263221,0.088712,2022-02-23 11:49:02.566
2,6215b8a9e5457239043adbef,2.0,1.0,less than mean,0.632996,0.040843,0.408823,0.657897,0.039796,2022-02-23 11:49:02.567
3,6215b8a9e5457239043adbf0,2.0,1.0,less than mean,0.543401,0.159890,0.303349,0.558807,0.157373,2022-02-23 11:49:02.567
4,6215b8a9e5457239043adbf1,2.0,1.0,0.510664,0.696249,0.255128,0.496977,0.725608,0.255970,NaT
5,6215b8a9e5457239043adbf2,2.0,1.0,less than mean,0.632996,0.374176,0.390878,0.657645,0.374735,2022-02-23 11:49:02.567
6,6215b8a9e5457239043adbf3,2.0,1.0,0.712552,0.554790,0.112271,0.750056,0.561494,0.114944,NaT
7,6215b8a9e5457239043adbf4,2.0,1.0,less than mean,0.298682,0.183700,0.281301,0.261433,0.182779,2022-02-23 11:49:02.567
8,6215b8a9e5457239043adbf5,2.0,1.0,less than mean,0.279367,0.302747,0.350860,0.233500,0.302196,2022-02-23 11:49:02.567
9,6215b8a9e5457239043adbf6,2.0,1.0,less than mean,0.357871,0.397985,0.229138,0.328729,0.398581,2022-02-23 11:49:02.567
10,6215b8a9e5457239043adbf7,2.0,1.0,less than mean,0.298682,0.517033,0.278752,0.269615,0.517330,2022-02-23 11:49:02.567
11,6215b8a9e5457239043adbf8,2.0,1.0,0.605258,0.720633,0.469414,0.613415,0.760009,0.469452,NaT
12,6215b8a9e5457239043adbf9,2.0,1.0,0.510664,0.696249,0.588462,0.521991,0.736991,0.588946,NaT
13,6215b8a9e5457239043adbfa,2.0,1.0,0.679005,0.701318,0.683700,0.718811,0.738577,0.682440,NaT
14,6215b8a9e5457239043adbfb,2.0,1.0,0.605258,0.720633,0.802747,0.649178,0.766301,0.801930,NaT
15,6215b8a9e5457239043adbfc,2.0,1.0,0.665708,0.456599,0.326557,0.680389,0.444562,0.327502,NaT
16,6215b8a9e5457239043adbfd,2.0,1.0,0.712552,0.554790,0.445605,0.737216,0.552056,0.443517,NaT
17,6215b8a9e5457239043adbfe,2.0,1.0,0.586043,0.367004,0.540843,0.591153,0.342069,0.540172,NaT
18,6215b8a9e5457239043adbff,2.0,1.0,0.665708,0.456599,0.659890,0.697242,0.441516,0.657521,NaT
19,6215b8a9e5457239043adc00,2.0,1.0,less than mean,0.445210,0.612271,0.249571,0.438057,0.614939,2022-02-23 11:49:02.567
20,6215b8a9e5457239043adc01,2.0,1.0,less than mean,0.357871,0.731319,0.262916,0.343512,0.732213,2022-02-23 11:49:02.567
21,6215b8a9e5457239043adc02,2.0,1.0,less than mean,0.543401,0.826557,0.320053,0.555754,0.827503,2022-02-23 11:49:02.567
22,6215b8a9e5457239043adc03,2.0,1.0,less than mean,0.445210,0.945605,0.262054,0.448170,0.943402,2022-02-23 11:49:02.567
23,6215b8a9e5457239043adc04,2.0,1.0,0.717298,0.642129,0.897985,0.770521,0.670869,0.898389,NaT
24,6215b8a9e5457239043adc05,2.0,1.0,less than mean,0.303751,0.755128,0.503560,0.274430,0.756290,2022-02-23 11:49:02.567
25,6215b8a9e5457239043adc06,2.0,1.0,0.586043,0.367004,0.874176,0.609000,0.342123,0.875088,NaT
26,6215b8a9e5457239043adc07,2.0,1.0,less than mean,0.279367,0.969414,0.385666,0.240071,0.969157,2022-02-23 11:49:02.567

In [61]:
coll2.drop()